research_task:
  description: >
    Conduzir uma pequisa sobre {topic}
    Encontre as informações mais relevantes e interessantes.
  expected_output: >
    Retornar um modelo pydantic sobre {topic}, com titulo, resumo em texto simples, url, timestamp e fonte.
  agent: researcher_agent

writing_task:
  description: >
    Escrever um resumo detalhado sobre {topic} com base nas informações fornecidas.
    O Resumo deve ter no mínimo 300 palavras e ser bem estruturado.
  expected_output: >
    Retornar um artigo estruturado em formato JSON, com suas respectivas específicações.
  agent: writer_agent
  inputs:
    researcher_output: research_task.output